-- 수냉이네 Vercel + Supabase V1
create table if not exists clients (
 id text primary key, sort_order int not null default 999, name text not null, affiliation text default '',
 grade text default 'C', source text not null default '수기', capacity int not null default 22,
 sunsang_group text, ship_name text, thefishing_uid text,
 captain_on boolean default true, captain_meal boolean default true,
 manager_on boolean default false, manager_meal boolean default false,
 soup_separate boolean default false, delivery text default '', reservation_url text default '', active boolean default true,
 unit_price int default 8000, vat_mode text default 'VAT별도', tax_enabled boolean default true,
 tax_cycle text default '월합산', tax_group text, memo text default '', created_at timestamptz default now()
);
create table if not exists orders (
 order_date date not null, client_id text references clients(id) on delete cascade,
 reservation int default 0, remaining int, prepared int default 0, paid int default 0, service int default 0,
 soup_count int default 0, unit_price int default 8000, supply_amount bigint default 0, vat_amount bigint default 0,
 total_amount bigint default 0, status text default '확인필요', confirm_method text default '', memo text default '',
 updated_at timestamptz default now(), primary key(order_date,client_id)
);
create table if not exists expenses (
 id bigint generated by default as identity primary key, expense_date date not null, type text not null,
 item text default '', amount bigint not null default 0, memo text default '', created_at timestamptz default now()
);
create table if not exists payments (
 id bigint generated by default as identity primary key, payment_date date not null, client_id text references clients(id),
 amount bigint not null default 0, memo text default '', unallocated_amount bigint default 0, created_at timestamptz default now()
);
create table if not exists payment_allocations (
 id bigint generated by default as identity primary key, payment_id bigint references payments(id) on delete cascade,
 order_date date not null, client_id text references clients(id), amount bigint not null default 0
);
create table if not exists settings (key text primary key, value text);
insert into settings(key,value) values
 ('finance_password_hash','03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4'),('opening_balance','0'),('owner_withdrawal','0')
on conflict(key) do nothing;

delete from clients;
insert into clients(id,sort_order,name,affiliation,grade,source,capacity,sunsang_group,ship_name,thefishing_uid,captain_on,captain_meal,manager_on,manager_meal,soup_separate,delivery,reservation_url,active,unit_price,vat_mode,tax_enabled,tax_cycle,tax_group) values
('c01',1,'가가호','피싱브로','A','선상24',22,'gagaho','가가호',null,true,true,false,false,true,'영목항','https://gagaho.sunsang24.com/ship/schedule_fleet',true,8000,'VAT별도',true,'월합산','가가호'),
('c02',2,'대한호','','A','선상24',20,'gagaho','대한호',null,true,true,false,false,true,'','https://gagaho.sunsang24.com/ship/schedule_fleet',true,8000,'VAT별도',true,'월합산','대한호'),
('c03',3,'비제이호','','A','선상24',22,'bj','비제이호',null,true,true,false,false,true,'','https://bj.sunsang24.com/ship/schedule_fleet',true,8000,'VAT별도',true,'월합산','비제이호'),
('c04',4,'홍단호','','A','선상24',22,'hongdan','홍단호',null,true,true,false,false,true,'','https://hongdanfishing.sunsang24.com/ship/schedule_fleet',true,8000,'VAT별도',true,'월합산','홍단호'),
('c05',5,'태극호','','B','선상24',22,'taeguk','태극호',null,true,true,false,false,false,'','https://taegeukho.sunsang24.com/ship/schedule_fleet',true,8000,'VAT별도',true,'월합산','태극호'),
('c06',6,'블랙이글스호','','B','선상24',22,'blackeagles','블랙이글스호',null,true,true,false,false,true,'','https://blackeagles.sunsang24.com/ship/schedule_fleet',true,8000,'VAT별도',true,'월합산','블랙이글스호'),
('c07',7,'레드맨','','B','선상24',16,'redman','레드맨호',null,true,true,false,false,false,'','https://redman.sunsang24.com/ship/schedule_fleet',true,8000,'VAT별도',true,'월합산','레드맨'),
('c08',8,'어울림호','','B','더피싱',15,null,'어울림호','3640',true,true,false,false,true,'','',true,8000,'VAT별도',true,'월합산','어울림호'),
('c09',9,'미르호','','B','더피싱',22,null,'미르호','5287',true,true,false,false,false,'초전항','',true,8000,'VAT별도',true,'월합산','미르+포세이돈'),
('c10',10,'포세이돈','','C','더피싱',9,null,'포세이돈호','5611',true,true,false,false,false,'초전항','',true,8000,'VAT별도',true,'월합산','미르+포세이돈'),
('c11',11,'연가호','','B','더피싱',17,null,'연가호','5245',true,true,false,false,false,'','',true,8000,'VAT별도',true,'월합산','연가호'),
('c12',12,'태백8호','','B','선상24',18,'taebaek','태백8호',null,true,true,false,false,true,'','https://taebaekho.sunsang24.com/ship/schedule_fleet',true,8000,'VAT별도',true,'월합산','태백8호'),
('c13',13,'태극1호(아버지)','','B','선상24',20,'taeguk','태극1호(아버지배)',null,true,true,false,false,true,'','https://taegeukho.sunsang24.com/ship/schedule_fleet',true,8000,'VAT별도',true,'월합산','태극1호(아버지)'),
('c14',14,'여명호','','A','선상24',22,'yeomyeong','여명호',null,true,true,false,false,true,'영목항','https://yeomyeongho.sunsang24.com/ship/schedule_fleet',true,8000,'VAT별도',true,'월합산','여명호'),
('c15',15,'스타호','','C','수기',17,null,'스타호',null,true,true,false,false,true,'','',true,8000,'VAT별도',true,'월합산','스타호'),
('c16',16,'레스비호','','C','수기',11,null,'레스비호',null,true,true,false,false,true,'','',true,8000,'VAT별도',true,'월합산','레스비호'),
('c17',17,'수연호','','C','수기',22,null,'수연호',null,true,true,false,false,true,'','',true,8000,'VAT별도',true,'월합산','수연호'),
('c18',18,'한하스페셜호','','C','수기',22,null,'한하스페셜호',null,true,true,false,false,true,'','',true,8000,'VAT별도',true,'월합산','한하스페셜호');

create table if not exists order_history (
 id bigint generated by default as identity primary key,
 order_date date not null, client_id text, action text not null, payload jsonb, created_at timestamptz default now()
);
